# Generated by Django 2.2.6 on 2019-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=50, verbose_name='Nome do Responsavel')),
                ('idade_resp', models.IntegerField(verbose_name='Idade do responsavel')),
                ('cpf', models.IntegerField(verbose_name='CPF do responsavel')),
                ('contato', models.IntegerField(verbose_name='Contato')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('nome_menor', models.CharField(max_length=50, verbose_name='Nome do menor')),
                ('idade_menor', models.IntegerField(verbose_name='Idade do menor')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
    ]
