# Generated by Django 2.2.6 on 2019-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menor_dezoito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menor',
            name='cpf_menor',
            field=models.IntegerField(verbose_name='CPF do menor'),
        ),
    ]
