# Generated by Django 2.2.6 on 2019-11-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menor_dezoito', '0002_auto_20191104_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menor',
            name='contato',
            field=models.IntegerField(verbose_name='Contato do responsavel'),
        ),
    ]
