# Generated by Django 2.2.6 on 2019-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('idade', models.IntegerField(max_length=50, verbose_name='Idade')),
                ('genero', models.CharField(max_length=50, verbose_name='Gênero')),
                ('cpf', models.IntegerField(max_length=50, verbose_name='CPF')),
                ('contato', models.IntegerField(max_length=50, verbose_name='Contato')),
                ('cep', models.IntegerField(max_length=50, verbose_name='CEP')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
    ]
